// <mcp-grid:generated>
// Generated by `mcp-grid integrate`. Edit the integration plan, not this block.
import { TooSClient } from "mcp-grid-client";

export const selectedMcpTools = [
  "client_onboard",
  "crm_followup",
  "extract_table_data",
  "extract_web_content",
  "find_replace",
  "invoice_remind",
  "lead_capture",
  "meeting_followup",
  "meeting_prepare",
  "modern_document_pdf",
  "playwright_screenshot",
  "project_complete",
  "proposal_accepted",
  "puppeteer_html_pdf",
  "astryx_docs",
  "playwright_responsive_capture",
  "playwright_webpage_pdf",
  "transform_text",
  "text_stats",
  "web_quality_audit",
  "hash_text",
  "base64_encode",
  "base64_decode",
  "generate_uuids",
  "seo_metadata_audit",
  "csv_to_json",
  "select_fields",
  "json_to_csv",
  "website_smoke_test"
] as const;
export const selectedMcpSkills = [
  {
    "id": "client_onboarding",
    "name": "Client Onboarding",
    "instructions": "Call client_onboard with the client name, primary contact, and service summary. Treat the returned artifact as the onboarding brief. Do not invent CRM, email, or calendar side effects; report pending_integrations exactly as returned. Prefer the business façade POST /api/lancee/client/onboard when the caller is a non-MCP app.",
    "tool_ids": [
      "client_onboard"
    ]
  },
  {
    "id": "content_normalization",
    "name": "Content Normalization",
    "instructions": "Use transform_text with the requested naming or case convention, apply find_replace only for explicit literal substitutions, then call text_stats when output size or limits matter. Preserve the original meaning and never describe these deterministic transforms as semantic rewriting.",
    "tool_ids": [
      "transform_text",
      "find_replace",
      "text_stats"
    ]
  },
  {
    "id": "invoice_recovery",
    "name": "Invoice Recovery",
    "instructions": "Call invoice_remind with invoice identity, client, amount due, and due date. Use the returned document as the recovery package. Do not claim the invoice was marked paid or that an email was sent unless a dedicated connector tool exists.",
    "tool_ids": [
      "invoice_remind"
    ]
  },
  {
    "id": "lead_qualification",
    "name": "Lead Qualification",
    "instructions": "Call lead_capture for each inbound lead. Use company_key as a stable slug when creating downstream records. Preserve original notes and report metrics without rewriting lead content.",
    "tool_ids": [
      "lead_capture"
    ]
  },
  {
    "id": "meeting_preparation",
    "name": "Meeting Preparation",
    "instructions": "Before a meeting call meeting_prepare with title, date, and agenda. Afterward call meeting_followup with summary and action items. Prefer these orchestration tools over rebuilding Markdown or PDF generation by hand.",
    "tool_ids": [
      "meeting_prepare",
      "meeting_followup"
    ]
  },
  {
    "id": "modern_pdf_publisher",
    "name": "Modern PDF Publisher",
    "instructions": "Prefer modern_document_pdf for reports, proposals, briefs, and documentation. Structure source Markdown with an executive summary, clear headings, short paragraphs, useful tables, and next steps. Choose executive for formal business material, minimal for technical documentation, editorial for narrative work, and midnight for presentation-style output. Use puppeteer_html_pdf only when exact custom HTML/CSS has already been supplied.",
    "tool_ids": [
      "modern_document_pdf",
      "puppeteer_html_pdf"
    ]
  },
  {
    "id": "production_web_evidence",
    "name": "Production Web Evidence",
    "instructions": "For an incident or verification request, audit the target URL first, capture the relevant page at an appropriate viewport, and optionally render the whole page to PDF. Record the final resolved URL, HTTP status, load time, audit issues, and returned artifact URLs. Do not browse private/internal addresses or represent an artifact as immutable archival evidence unless it has been copied into the organization's governed evidence store.",
    "tool_ids": [
      "playwright_screenshot",
      "playwright_webpage_pdf",
      "web_quality_audit"
    ]
  },
  {
    "id": "safe_encoding_utilities",
    "name": "Safe Encoding Utilities",
    "instructions": "Use hash_text for content fingerprints, base64_encode or base64_decode only for transport encoding, and generate_uuids for opaque identifiers. Explicitly state that Base64 is not encryption and that unsalted hashes are not suitable for password storage.",
    "tool_ids": [
      "hash_text",
      "base64_encode",
      "base64_decode",
      "generate_uuids"
    ]
  },
  {
    "id": "sales_follow_up",
    "name": "Sales Follow-up",
    "instructions": "For new inbound interest call lead_capture. For existing opportunities call crm_followup with the last touchpoint and next action. Keep provider-specific CRM writes out of scope; surface pending_integrations for later connector work.",
    "tool_ids": [
      "lead_capture",
      "crm_followup"
    ]
  },
  {
    "id": "seo_content_review",
    "name": "SEO Content Review",
    "instructions": "Call seo_metadata_audit first, then web_quality_audit for the same canonical page. Separate missing technical metadata from visible content and accessibility issues. Prioritize title, description, canonical URL, indexability, Open Graph, structured data, headings, and image alternatives. Report observed facts and avoid promising ranking outcomes.",
    "tool_ids": [
      "seo_metadata_audit",
      "web_quality_audit"
    ]
  },
  {
    "id": "tabular_data_exchange",
    "name": "Tabular Data Exchange",
    "instructions": "Inspect headers before conversion, use csv_to_json for delimited input, select_fields to enforce the required output columns, and json_to_csv only after the record structure is consistent. State row limits and never claim truncated or rejected input was fully converted.",
    "tool_ids": [
      "csv_to_json",
      "select_fields",
      "json_to_csv"
    ]
  },
  {
    "id": "web_research_report",
    "name": "Web Research to Report",
    "instructions": "Call extract_web_content for each public source URL and preserve source URLs in the notes. Capture a screenshot when visual evidence matters. Distinguish extracted facts from inference, synthesize rather than copy, and call modern_document_pdf only after the report includes sources, findings, recommendations, and limitations.",
    "tool_ids": [
      "extract_web_content",
      "playwright_screenshot",
      "modern_document_pdf"
    ]
  },
  {
    "id": "web_table_extraction",
    "name": "Web Table Extraction",
    "instructions": "Use extract_table_data with the narrowest stable table selector available and an explicit row limit. Preserve the resolved source URL, headers, total row count, and truncation flag. Use extract_web_content only when surrounding text is needed to interpret the table. Never silently infer missing cells or treat truncated output as the complete dataset.",
    "tool_ids": [
      "extract_table_data",
      "extract_web_content"
    ]
  },
  {
    "id": "website_release_gate",
    "name": "Website Release Gate",
    "instructions": "Before approving a web release, call web_quality_audit on the public candidate URL, then call playwright_responsive_capture. Summarize blocking issues first, include the audit score, verify mobile/tablet/desktop evidence, and never claim a pass when the audit reports unresolved browser errors or essential metadata failures.",
    "tool_ids": [
      "web_quality_audit",
      "playwright_responsive_capture"
    ]
  },
  {
    "id": "website_smoke_testing",
    "name": "Website Smoke Testing",
    "instructions": "Call website_smoke_test with explicit title, text, or selector expectations derived from the acceptance criteria. Report every check and its actual value. If any check fails, call playwright_screenshot for the same URL and include the temporary evidence link. Do not turn a partial check into a release approval.",
    "tool_ids": [
      "website_smoke_test",
      "playwright_screenshot"
    ]
  }
] as const;

let mcpGridClient: TooSClient | undefined;

export function getMcpGridClient(): TooSClient {
  const token = process.env.MCP_API_TOKEN;
  if (!token) throw new Error("MCP_API_TOKEN is required");
  mcpGridClient ??= new TooSClient(
    process.env.MCP_GATEWAY_URL ?? "https://mcp.hygridtech.co.za",
    token,
  );
  return mcpGridClient;
}

export async function invokeMcpTool(
  toolId: (typeof selectedMcpTools)[number],
  arguments_: Record<string, unknown> = {},
) {
  if (!(selectedMcpTools as readonly string[]).includes(toolId)) {
    throw new Error(`Tool ${toolId} is not enabled by this integration`);
  }
  return getMcpGridClient().invoke(toolId, arguments_);
}
// </mcp-grid:generated>
